### ISSUE TITLE
Syncthing version 1.0.1? Nemo integration?

### ISSUE THREAD

**Issue by GoSpursGoNL** [kozec/syncthing-gtk#528] opened 2019-09-15 11:28 UTC
Hi, I installed syncthing-gtk under Linux Mint 19.2 (new installation). I used the Ubuntu 18.04 OpenSuse PPA since Mint 19.2 is based on Ubuntu 18.04. I got Syncthing-gtk 0.9.4.4 according to Synaptic. Inside Syncthing-gtk in the About window, no version is mentioned though.

Anyway, in the settings I have activated 'Keep syncthing binary up-to-date'. Now I see that Syncthing version 1.0.1 is running. Why is it not being upgraded to a later version? Yesterday the Syncthing binary was suddenly not found by Syncthing-GTK by the way. I used the built-in functionality to have it downloaded.

A second problem: I have Nemo-integration activated. But inside Nemo I don't see any special icons in the synced folders.

**Comment by kozec** [comment] 2019-09-18 21:03
Not updating to latest version should be fixed (again), but Nemo-integration issue is most likely caused by Nemo version in your distro dropping support for python2 plugins.

**Comment by Salamandar** [comment] 2019-10-01 15:28
I confirm that Syncthing-gtk still using py2 is the cause of why the Nemo plugin does not work.

**Closed** 2023-04-09 08:55 UTC
